name: xnap-example
channels:
- pytorch
- defaults
dependencies:
- python=3.8
- numpy
- tqdm
- tensorboard
- protobuf<=3.20
- pip
- pip:
  - --extra-index-url https://download.pytorch.org/whl/cu113
  - torch==1.12.1+cu113
  - torchvision==0.13.1+cu113
  - torchaudio==0.12.1
  - onnx
  - wandb
  - onnxruntime
  - ipykernel
